### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by eladcandroid** [thaiat/fuse-demo-angular2#1]
Windows 7
node v6.9.2
fuse v0.33.0

npm run build

> fuse-demo-3@0.0.1 build C:\Users\eladco\dev\angular2\fuse-demo-angular2
> webpack --progress --profile --display-error-details --display-cached

module.js:471
    throw err;
    ^

Error: Cannot find module './plugins/PostCompilePlugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\eladco\dev\angular2\fuse-demo-angular2\webpack.config.js:8:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\eladco\dev\angular2\fuse-demo-angular2\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\Users\eladco\dev\angular2\fuse-demo-angular2\node_modules\webpack\bin\webpack.js:39:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\eladco\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! fuse-demo-3@0.0.1 build: `webpack --progress --profile --display-error-details --display-cached`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fuse-demo-3@0.0.1 build script 'webpack --progress --profile --display-error-details --display-cached'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fuse-demo-3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --profile --display-error-details --display-cached
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fuse-demo-3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fuse-demo-3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\eladco\dev\angular2\fuse-demo-angular2\npm-debug.log

**Comment by andresg747** [comment]
Hi,

Same error here. Any updates on this?

**Comment by FirstAmendmentware** [comment]
Same here.
